// Permission codes aligned with docs/08-api/authorization.md.
// Format: "action:resource".
export const PermissionCode = {
  CreateMaterial: 'create:material',
  EditMaterial: 'edit:material',
  CreateLocation: 'create:location',
  EditLocation: 'edit:location',
  DeleteLocation: 'delete:location',
  ManageLocationStatus: 'manage:location_status',
  CreateSupplier: 'create:supplier',
  EditSupplier: 'edit:supplier',
  ViewPurchaseOrder: 'view:purchase_order',
  CreatePurchaseOrder: 'create:purchase_order',
  SubmitPurchaseOrder: 'submit:purchase_order',
  ApprovePurchaseOrder: 'approve:purchase_order',
  CancelPurchaseOrder: 'cancel:purchase_order',
  ShipPurchaseOrder: 'ship:purchase_order',
  DeliverPurchaseOrder: 'deliver:purchase_order',
  ViewGoodsReceipt: 'view:goods_receipt',
  ReceiveInventory: 'receive:inventory',
  IssueInventory: 'issue:inventory',
  TransferInventory: 'transfer:inventory',
  AdjustInventory: 'adjust:inventory',
  CheckOutTool: 'checkout:tool',
  CheckInTool: 'checkin:tool',
  ManageUsers: 'manage:users',
  ViewUsers: 'view:users',
  ManageRoles: 'manage:roles',
  ViewReports: 'view:reports',
  ViewAuditLog: 'view:audit_log',
  ManageRacks: 'manage:racks',
  ManageProjects: 'manage:projects',
  ManageSettings: 'manage:settings',
  UpdateInventoryTransaction: 'update:inventory_transaction',
} as const;

export type PermissionCodeValue = (typeof PermissionCode)[keyof typeof PermissionCode];

export const ALL_PERMISSION_CODES: PermissionCodeValue[] = Object.values(PermissionCode);

export const RolePermissions: Record<string, PermissionCodeValue[]> = {
  ADMIN: [
    ...ALL_PERMISSION_CODES,
  ],
  STORE_CONTROLLER: [
    PermissionCode.CreateMaterial,
    PermissionCode.EditMaterial,
    PermissionCode.CreateLocation,
    PermissionCode.EditLocation,
    PermissionCode.DeleteLocation,
    PermissionCode.ManageLocationStatus,
    PermissionCode.ReceiveInventory,
    PermissionCode.IssueInventory,
    PermissionCode.TransferInventory,
    PermissionCode.AdjustInventory,
    PermissionCode.CheckOutTool,
    PermissionCode.CheckInTool,
    PermissionCode.ManageRacks,
    PermissionCode.ManageProjects,
    PermissionCode.ViewPurchaseOrder,
    PermissionCode.ShipPurchaseOrder,
    PermissionCode.DeliverPurchaseOrder,
    PermissionCode.ViewGoodsReceipt,
    PermissionCode.ViewReports,
    PermissionCode.ViewUsers,
    PermissionCode.UpdateInventoryTransaction,
  ],
  PROCUREMENT: [
    PermissionCode.CreateSupplier,
    PermissionCode.EditSupplier,
    PermissionCode.ViewPurchaseOrder,
    PermissionCode.CreatePurchaseOrder,
    PermissionCode.SubmitPurchaseOrder,
    PermissionCode.CancelPurchaseOrder,
    PermissionCode.ReceiveInventory,
    PermissionCode.ViewGoodsReceipt,
    PermissionCode.ManageProjects,
    PermissionCode.ViewReports,
  ],
  APPROVER: [PermissionCode.ApprovePurchaseOrder, PermissionCode.ViewReports],
  TECHNICIAN: [
    PermissionCode.IssueInventory,
    PermissionCode.CheckOutTool,
    PermissionCode.CheckInTool,
    PermissionCode.ViewReports,
    PermissionCode.ViewUsers,
  ],
  VIEWER: [PermissionCode.ViewReports],
};